<?php
/**
 * Theme options
 *
 * WARNING! DO NOT EDIT THIS FILE!
 * Editing below this line should NOT be necessary.
 * Change at your own risk.
 *
 * @package Wordspop
 * @subpackage Wordspop_Framework_Theme
 * @since Wordspop Framework Theme 1.0
 */

$options = array(

    // General
    array(
        'type'      => 'general',
     
    ),
    array(
        'type'      => 'select',
        'title'     => __('Pictures Excerpt'),
        'name'      => 'pic_excerpt',
        'desc'      => __('How many pictures will show on "pictures in this set"'),
        'options'   => array(
				        '2'    	=> __('Two'),
				        '4'  	=> __('Four'),
				        '6'  	=> __('Six'),
				        '8' 	=> __('Eight'),
				        )
    ),
    array(
    	'type'		=> 'typography'
    ),
    array(
    	'type'		=> 'styling'
    ),
    // Header Section
    array(
        'type'      => 'header'
    ),
    
    // Footer Section
    array(
        'type'      => 'footer'
    )
);
