exclude: ['*.sublime-project', '*.sublime-workspace', 'README.md']
markdown: redcarpet
redcarpet:
    extensions: ['smart', 'autolink', 'strikethrough', 'space_after_headers', 'superscript']
permalink: pretty
tagline: 'Hi, I&rsquo;m <b>Amsul</b>. I <b>develop</b> &amp; <b>design</b> stuff for our web.'
url: http://amsul.ca/
url_github: https://github.com/amsul/
emoji_dir: https://github.global.ssl.fastly.net/images/icons/emoji/
paginate: 3
paginate_path: 'page/:num'