exclude: [ '*.sublime-project', '*.sublime-workspace', 'README.md' ]
markdown: rdiscount
permalink: pretty
tagline: 'Hi, I&rsquo;m Amsul. I develop &amp; design stuff for our interwebs.'
url: http://amsul.ca/
url_github: https://github.com/amsul/
emoji_dir: https://github.global.ssl.fastly.net/images/icons/emoji/